# PyTorch - the Basics!

Advanced Learning 2024

Lee Carlin

For SUBMISSION:
~~~
STUDENT ID: 314757212
~~~
~~~
STUDENT GIT LINK: https://github.com/NatanLishinskyFischer/52025
~~~
In Addition, don't forget to add your ID to the files:
`PS0_PyTorch_basics_2024_ID_[000000000].ipynb`  
`PS0_PyTorch_basics_2024_ID_[000000000].html`  

## 1. What is PyTorch?


PyTorch is a popular open-source library for machine learning, particularly well-suited for deep learning applications.    
Here's a breakdown of its key features:

    

*   **Deep Learning Framework:**  PyTorch provides tools and functionalities to  build and train complex neural networks.
*   **Pythonic Interface:**  Known for its Python-like syntax, PyTorch is considered user-friendly and easy to learn.
* **Flexibility:**  PyTorch offers both dynamic computational graphs (eager execution) and static graphs (graph mode) for model development.
* **Production Ready:**  PyTorch provides features like TorchScript to transition models from development to production seamlessly.
* **Scalability:**  PyTorch supports distributed training, enabling you to leverage multiple CPUs or GPUs to train models faster.
* **Rich Ecosystem:**  A growing ecosystem of libraries and tools built on PyTorch expands its capabilities for tasks like computer vision, natural language processing, and model interpretability.




    
    

    

    
    



We start by importing PyTorch's main objects:

In [1]:
import torch
from torch import nn

### PyTorch Main Modules

`torch.nn`:

In PyTorch, the `torch.nn` module provides the essential building blocks you need to construct and train neural networks. It offers a comprehensive collection of classes and functions that streamline the deep learning development process.  
  
*Key Components:*  

**Modules**:   
These are the fundamental units that perform specific operations on data. They can be combined to create complex neural network architectures. Common examples include:   

* Linear Layers (nn.Linear): Apply linear transformations (y = xA^T + b) for feeding data forward through the network.
* Convolutional Layers (nn.Conv2d): Perform convolutions, especially useful for processing image data.
* Activation Layers (nn.ReLU, nn.Sigmoid): Introduce non-linearity into the network, allowing it to learn complex patterns.
* Normalization Layers (nn.BatchNorm2d): Normalize inputs to layers for faster and more stable training.
* Recurrent Layers (nn.LSTM, nn.GRU): Handle sequential data like text or time series.
* Dropout Layers (nn.Dropout): Introduce randomness by randomly dropping out neurons during training to prevent overfitting.
* Many More: PyTorch offers a vast selection of modules catering to diverse neural network architectures.

**Containers**:   
These classes help you organize and structure your modules into hierarchical networks. They include:
* nn.Sequential: Stacks modules in a linear sequence, making it easy to define simple neural networks.
* nn.ModuleList: Holds other modules in a list, allowing for more flexible network structures.
* nn.ModuleDict: Manages sub-modules with dictionary-like access for complex topologies.

**Loss Functions:**   
Functions that measure the error between the network's predictions and the ground truth labels. These guide the training process by calculating the gradients used to update the network's weights. Common examples include:
* nn.CrossEntropyLoss: For multi-class classification problems.
* nn.MSELoss: For mean squared error calculations in regression tasks.



In [4]:
from torch.utils.data import DataLoader


`torch.utils.data.DataLoader`:

In PyTorch, `torch.utils.data.DataLoader` is a powerful tool that simplifies how you load and manage data for training your deep learning models. It acts as an iterator, efficiently providing batches of data during the training process.

Here's a breakdown of its key functionalities:

Data Management Abstraction:

    Decouples data loading logic from your model training code, promoting cleaner and more maintainable code.
    Handles complexities like batching, shuffling, and multi-processing data loading, freeing you from writing repetitive code.

Efficient Batching:

    Groups data samples (images, text, etc.) into batches of a specified size (batch_size). Batching improves computational efficiency by utilizing vectorized operations on GPUs.
    Provides an optional collate_fn argument that allows you to customize how samples within a batch are combined. This can be useful for tasks like padding sequences to have the same length.

In [6]:
torch.__version__

'2.5.1+cpu'

In our course we use PyTorch version >=2.2.1.   
`cu121` refers to CUDA 12.1, a software layer that gives direct access to the GPU's virtual instruction set and parallel computational elements for the execution of compute kernels.

## 2. Tensors

In PyTorch, tensors are the fundamental data structure. They are similar to NumPy arrays but with some key advantages for deep learning:

* **Multi-dimensional Arrays**: Like NumPy arrays, tensors can have multiple dimensions, making them suitable for representing data like images (2D), videos (3D), or sequences of text (1D).

* **Hardware Acceleration**: PyTorch tensors can be moved to and run on GPUs or other hardware accelerators, significantly speeding up computations compared to CPUs for deep learning tasks.

* **Automatic Differentiation**:  A core feature in deep learning, automatic differentiation allows PyTorch to calculate gradients efficiently, which is essential for training neural networks.  Regular NumPy arrays don't inherently support this.

* **Rich Functionality**: PyTorch offers a variety of operations specifically designed for tensors, making it convenient to manipulate and analyze data for deep learning models.

In essence, tensors in PyTorch act as the workhorses for your deep learning models. They store and process the data that gets fed into your network, undergoes computations, and ultimately leads to predictions or outputs.


**PyTorch tensor operations:**

PyTorch tensor operations are the fundamental building blocks for working with data in your deep learning models. These operations allow you to manipulate, analyze, and transform tensors in various ways. Here's a breakdown of some common categories:

1. Arithmetic Operations:

These operations perform element-wise calculations between tensors or a tensor and a scalar value. They include:

    Addition (+)
    Subtraction (-)
    Multiplication (*)
    Division (/)
    Exponentiation (**)

These operations can be used for simple calculations or combined to create more complex expressions.

2. Comparison Operations:

These operations compare elements between tensors or a tensor and a scalar value, resulting in a tensor of booleans (True or False) indicating the comparison outcome. Examples include:

    Equal (==)
    Not equal (!=)
    Greater than (>)
    Less than (<)
    Greater than or equal (>=)
    Less than or equal (<=)

Comparison operations are useful for filtering data or making decisions within your model.

3. Broadcasting:

A powerful feature in PyTorch, broadcasting allows operations between tensors of different shapes as long as they are compatible. For instance, you can add a scalar value to a tensor, or add a one-dimensional tensor to a two-dimensional tensor (as long as the dimensions match). PyTorch automatically expands the smaller tensor to match the larger one for element-wise operations.

4. In-place Operations:

Certain operations modify the original tensor they are applied to, denoted by a trailing underscore (_). Examples include:

    x.add_(y) (equivalent to x = x + y)
    x.sub_(y) (equivalent to x = x - y)
    x.mul_(y) (equivalent to x = x * y)

These operations can be memory-efficient when modifying existing tensors is desired.

5. Linear Algebra Operations:

PyTorch provides functions for common linear algebra operations on tensors, including:

    torch.matmul(a, b): Matrix multiplication between tensors a and b.
    torch.sum(input, dim=None): Sums the elements of a tensor along a specified dimension.
    torch.mean(input, dim=None): Computes the mean of the elements of a tensor along a specified dimension.

These operations are essential for various deep learning tasks like calculating activation outputs or loss functions.

6. Tensor Reshaping and Indexing:

PyTorch offers functionalities to manipulate the shape and access specific elements of tensors:

    x.view(new_shape): Reshapes the tensor x into a new shape while keeping the total number of elements the same.
    x[index]: Accesses specific elements or sub-tensors using indexing syntax (similar to NumPy).

Reshaping and indexing are crucial for preparing data for specific layers in your neural network architecture.

7. Element-wise Operations:

These operations apply a function to each element of a tensor independently. PyTorch provides a rich set of element-wise functions like:

    torch.relu(x): Applies the rectified linear unit (ReLU) activation function.
    torch.sigmoid(x): Applies the sigmoid activation function.
    torch.tanh(x): Applies the hyperbolic tangent (tanh) activation function.

Element-wise operations are fundamental for introducing non-linearity and transforming data in deep learning models.

8. Random Operations:

PyTorch offers functions for generating random tensors or modifying existing ones with randomness:

    torch.rand(shape): Generates a random tensor filled with uniformly distributed values between 0 and 1.
    torch.randn(shape): Generates a random tensor filled with values from a standard normal distribution.

These operations are useful for data augmentation techniques or initializing weights in your network.

By understanding and effectively using these PyTorch tensor operations, you can build and manipulate your deep learning models with greater flexibility and control.

Some examples:

In [11]:
lst_of_lsts = [[1, 2, 3, 4],[5, 6, 7, 8]]
tens = torch.tensor(lst_of_lsts)
print(f"tens: {tens}")
print(f"Shape of tensor: {tens.shape}")
print(f"Datatype of tensor: {tens.dtype}")
print(f"Device tensor is stored on: {tens.device}")


tens: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Shape of tensor: torch.Size([2, 4])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [12]:
shape = (2,2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.5230, 0.7089, 0.6531],
         [0.5233, 0.0326, 0.4482]],

        [[0.0814, 0.0635, 0.7062],
         [0.1562, 0.5017, 0.8617]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [13]:
shpe = (100,3)
t1 = torch.rand(shpe)
t2 = torch.rand(shpe)
t3 = torch.rand(shpe)
t4=torch.cat([t1,t2,t3],dim=0)
print(f"t4.shape: {t4.shape}")
t5=torch.cat([t1,t2,t3],dim=1)
print(f"t5.shape: {t5.shape}")

t4.shape: torch.Size([300, 3])
t5.shape: torch.Size([100, 9])


In [20]:
X = torch.rand(100,100)
X_cent = X - X.mean(dim=1, keepdim=True)
covX = X_cent.T@X_cent
covX

tensor([[ 6.2942,  0.1581, -0.4518,  ..., -0.1013,  0.3129, -0.4592],
        [ 0.1581,  9.0172,  0.7331,  ..., -0.6976,  0.3696,  0.1333],
        [-0.4518,  0.7331,  7.4482,  ...,  0.3755, -1.6807,  1.1175],
        ...,
        [-0.1013, -0.6976,  0.3755,  ...,  7.2872,  0.6120, -1.4579],
        [ 0.3129,  0.3696, -1.6807,  ...,  0.6120,  7.7742, -0.3622],
        [-0.4592,  0.1333,  1.1175,  ..., -1.4579, -0.3622,  7.7959]])

## Data & Handling

### PyTorch Datasets

Deep networks are versatile tools that can be adapted to various data types by
leveraging appropriate pre-processing techniques and network architectures.
PyTorch, like other deep learning libraries, can handle a wide array of data:
  


* images
* audio
* text data
* tabluar (numerical, categorical, mixed)
* multimodal Data
* other



PyTorch also offers built-in vision specific datasets as part of the `torchvision.datasets` [module](https://pytorch.org/vision/stable/datasets.html):

In [26]:
from torchvision import datasets

In [29]:
dir(datasets)

['CIFAR10',
 'CIFAR100',
 'CLEVRClassification',
 'CREStereo',
 'Caltech101',
 'Caltech256',
 'CarlaStereo',
 'CelebA',
 'Cityscapes',
 'CocoCaptions',
 'CocoDetection',
 'Country211',
 'DTD',
 'DatasetFolder',
 'EMNIST',
 'ETH3DStereo',
 'EuroSAT',
 'FER2013',
 'FGVCAircraft',
 'FakeData',
 'FallingThingsStereo',
 'FashionMNIST',
 'Flickr30k',
 'Flickr8k',
 'Flowers102',
 'FlyingChairs',
 'FlyingThings3D',
 'Food101',
 'GTSRB',
 'HD1K',
 'HMDB51',
 'INaturalist',
 'ImageFolder',
 'ImageNet',
 'Imagenette',
 'InStereo2k',
 'KMNIST',
 'Kinetics',
 'Kitti',
 'Kitti2012Stereo',
 'Kitti2015Stereo',
 'KittiFlow',
 'LFWPairs',
 'LFWPeople',
 'LSUN',
 'LSUNClass',
 'MNIST',
 'Middlebury2014Stereo',
 'MovingMNIST',
 'Omniglot',
 'OxfordIIITPet',
 'PCAM',
 'PhotoTour',
 'Places365',
 'QMNIST',
 'RenderedSST2',
 'SBDataset',
 'SBU',
 'SEMEION',
 'STL10',
 'SUN397',
 'SVHN',
 'SceneFlowStereo',
 'Sintel',
 'SintelStereo',
 'StanfordCars',
 'UCF101',
 'USPS',
 'VOCDetection',
 'VOCSegmentation',
 

In [31]:
from torchvision.transforms import ToTensor
train_source = training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)
train_source

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [32]:
type(train_source)

torchvision.datasets.mnist.FashionMNIST

In [33]:
print(f"the shape of the data: {train_source.data.shape}")

the shape of the data: torch.Size([60000, 28, 28])


We can visualize the data using matplotlib:

In [35]:
import matplotlib.pyplot as plt

In [ ]:
labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}
figure = plt.figure(figsize=(8, 8))
cols, rows = 5, 2
for i in range(1, cols * rows + 1):
    sample_idx = torch.randint(len(train_source), size=(1,)).item()
    img, label = train_source[sample_idx]
    figure.add_subplot(rows, cols, i)
    plt.title(labels_map[label])
    plt.axis("off")
    plt.imshow(img.squeeze(), cmap="gray")
plt.show()

### DataLoader

As mentioned above, the `torch.utils.data.DataLoader` is responsible for handling data during the deep learning model training.

Key Parameters:

* dataset (Dataset): The PyTorch dataset you want to load data from (your custom class representing the data and how to access samples and labels).
* batch_size (int, optional): The number of samples in a batch (default: 1).
* shuffle (bool, optional): Whether to shuffle the data at the beginning of each epoch (default: False).
* sampler (Sampler, optional): A custom sampler object for controlling data loading order (default: None).
* collate_fn (callable, optional): A function to customize how samples within a batch are combined (default: None). Useful for padding sequences.
* pin_memory=True (bool, optional): If using a GPU, pin fetched data tensors in pinned memory for faster transfer (default: False).

In [ ]:
train = DataLoader(train_source, batch_size=64, shuffle=True)
type(train)



> The Dataset retrieves our dataset’s features and labels one sample at a time. While training a model, we typically want to pass samples in “minibatches”, reshuffle the data at every epoch to reduce model overfitting, and use Python’s multiprocessing to speed up data retrieval.



In [ ]:
for i in range(5):
  btch = next(iter(train))
  print(f"batch shape: {btch[0].shape}")

## Practice Questions

Produce the following tensors:  

1. Create a tensor from the list `[1, 2, 3]`
2. Create a tensor from a NumPy array of shape (50,10)
3. Specify a data type and device option for a tensor with `[7, 8, 9]`, `[.5,0,.7]`
4. Create a zero tensor of size (3, 4)
5. Create a ones tensor of size (2, 2, 2) with dtype float
6. Create a tensor of size (5, 5) with random values from a normal distribution
7. Create a new tensor by cloning an existing tensor
8. Create a new tensor by reshaping an existing tensor
9. Create a new tensor by concatenating two existing tensors
10.  Perform operations with different data types

In [38]:
import numpy as np

tensor_from_list = torch.tensor([1, 2, 3])
print(tensor_from_list)

numpy_array = np.random.rand(50, 10)
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy.shape)

tensor_int = torch.tensor([7, 8, 9], dtype=torch.int32, device='cpu')
tensor_float = torch.tensor([0.5, 0, 0.7], dtype=torch.float32, device='cpu')
print(tensor_int)
print(tensor_float)

zero_tensor = torch.zeros(3, 4)
print(zero_tensor)

ones_tensor = torch.ones(2, 2, 2, dtype=torch.float)
print(ones_tensor)

normal_tensor = torch.randn(5, 5)
print(normal_tensor)

existing_tensor = torch.tensor([1, 2, 3])
cloned_tensor = existing_tensor.clone()
print(cloned_tensor)

reshaped_tensor = tensor_from_numpy.view(10, 50)  # Change shape (50, 10) to (10, 50)
print(reshaped_tensor.shape)

tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
concatenated_tensor = torch.cat((tensor_a, tensor_b), dim=0)
print(concatenated_tensor)

int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([0.1, 0.2, 0.3], dtype=torch.float32)

result_tensor = int_tensor.float() + float_tensor
print(result_tensor)



tensor([1, 2, 3])
torch.Size([50, 10])
tensor([7, 8, 9], dtype=torch.int32)
tensor([0.5000, 0.0000, 0.7000])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[ 1.1634,  0.5063,  0.1047, -0.8668, -0.1962],
        [-1.6226, -1.8204,  0.7913,  0.9354,  0.8874],
        [-0.4868, -0.4219, -1.4298,  0.2061,  1.0446],
        [ 0.2578, -0.6737,  1.4116,  0.0680, -2.1021],
        [-1.4526, -0.7953,  0.0475,  0.0931,  0.3429]])
tensor([1, 2, 3])
torch.Size([10, 50])
tensor([1, 2, 3, 4, 5, 6])
tensor([1.1000, 2.2000, 3.3000])


1. Inspect the  attributes of some of the tensors you created with `shape,dtype,numel`.
2. Indexing to access specific elements: `[[1, 2, 3], [4, 5, 6]]`, get the '2' element.

3. Modify modify the '5' element to '10'
4. Apply element-wise addition to two tensors.
5. Apply element-wise multiplication to two tensors
6. Apply a square root to a tensor.
7. Create a tensor with random values from a uniform distribution between 0 and 1.
8. Create a tensor with random values from a normal distribution with mean 0 and standard deviation 1
9. Create a tensor with random values from a discrete uniform distribution between 1 and 10.
10. Reshape a tensor from size `(2, 3)` to `(3, 2)`
11. Transpose a tensor
12. Concatenate tensors along a specific dimension
13. Stack tensors along a new dimension


In [52]:
print("Shape:", tensor_from_list.shape)
print("Dtype:", tensor_from_list.dtype)
print("Numel (number of elements):", tensor_from_list.numel())

print("Shape:", normal_tensor.shape)
print("Dtype:", normal_tensor.dtype)
print("Numel:", normal_tensor.numel())

matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
element_2 = matrix[0, 1]  # 0th row, 1st column
print(element_2)

matrix[1, 1] = 10  # 1st row, 1st column
print(matrix)

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
added_tensor = tensor1 + tensor2
print(added_tensor)

multiplied_tensor = tensor1 * tensor2
print(multiplied_tensor)

sqrt_tensor = torch.sqrt(torch.tensor([1.0, 4.0, 9.0]))
print(sqrt_tensor)

uniform_tensor = torch.rand(3, 3)
print(f"uniform tensor: {uniform_tensor}")

normal_dist_tensor = torch.randn(3, 3)
print(normal_dist_tensor)

discrete_uniform_tensor = torch.randint(1, 11, (3, 3))
print(discrete_uniform_tensor)

reshaped_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]]).view(3, 2)
print(reshaped_tensor)

transposed_tensor = reshaped_tensor.T  # Alternatively, use .transpose(0, 1)
print(transposed_tensor)

concat_tensor = torch.cat((tensor1.unsqueeze(0), tensor2.unsqueeze(0)), dim=0)
print(concat_tensor)

stacked_tensor = torch.stack((tensor1, tensor2), dim=1)
print(stacked_tensor)

Shape: torch.Size([3])
Dtype: torch.int64
Numel (number of elements): 3
Shape: torch.Size([5, 5])
Dtype: torch.float32
Numel: 25
tensor(2)
tensor([[ 1,  2,  3],
        [ 4, 10,  6]])
tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([1., 2., 3.])
uniform tensor: tensor([[0.7467, 0.6716, 0.4043],
        [0.6495, 0.8306, 0.1350],
        [0.4308, 0.9468, 0.5678]])
tensor([[-0.7878, -0.5151, -2.1047],
        [ 0.1527,  0.0909, -1.4026],
        [-0.6634,  0.7634, -0.7610]])
tensor([[9, 8, 7],
        [3, 3, 1],
        [6, 2, 4]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 3, 5],
        [2, 4, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


1. Sum of all elements in a tensor.
2. Mean along a specific dimension
3. Find the minimum and maximum values in a tensor
4. Find the indices of minimum and maximum values in a tensor


In [54]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
sum_of_elements = torch.sum(tensor)
print("Sum of all elements:", sum_of_elements)

mean_dim0 = torch.mean(tensor.float(), dim=0) 
print("Mean along dimension 0:", mean_dim0)

# Mean along dimension 1 (row-wise mean):
mean_dim1 = torch.mean(tensor.float(), dim=1)
print("Mean along dimension 1:", mean_dim1)

min_value = torch.min(tensor)
max_value = torch.max(tensor)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

min_index = torch.argmin(tensor)
max_index = torch.argmax(tensor)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)


Sum of all elements: tensor(21)
Mean along dimension 0: tensor([2.5000, 3.5000, 4.5000])
Mean along dimension 1: tensor([2., 5.])
Minimum value: tensor(1)
Maximum value: tensor(6)
Index of minimum value: tensor(0)
Index of maximum value: tensor(5)


Broadcasting:

In [57]:

# Broadcasting with scalars
tensor_a = torch.tensor([1, 2, 3])
scalar_b = 5
result_broadcast_scalar = tensor_a + scalar_b
print("Broadcasting with scalars:")
print(result_broadcast_scalar)  # Output: tensor([6, 7, 8])

# Broadcasting with different shapes
tensor_c = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_d = torch.tensor([10, 20, 30])
result_broadcast_shape = tensor_c + tensor_d
print("Broadcasting with different shapes:")
print(result_broadcast_shape)

Broadcasting with scalars:
tensor([6, 7, 8])
Broadcasting with different shapes:
tensor([[11, 22, 33],
        [14, 25, 36]])


In [59]:
# Broadcasting with multidimensional tensors
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([10, 20, 30])
result_broadcast = tensor_a + tensor_b
print("Broadcasting with multidimensional tensors:")
print(result_broadcast)

# Common broadcasting pitfalls
tensor_c = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_d = torch.tensor([10, 20])
# The following line will raise a RuntimeError
try:
    result_pitfall = tensor_c + tensor_d
except RuntimeError as e:
    print("RuntimeError:", e)

Broadcasting with multidimensional tensors:
tensor([[11, 22, 33],
        [14, 25, 36]])
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1


Device specification

In [62]:
# Code examples for device configuration and availability

# Check if GPU is available
is_gpu_available = torch.cuda.is_available()
print("Is GPU available?", is_gpu_available)

# Specify device for tensor operations
device = torch.device('cuda' if is_gpu_available else 'cpu')
tensor_gpu = torch.tensor([1, 2, 3], device=device)
print("Tensor on GPU:", tensor_gpu)


Is GPU available? False
Tensor on GPU: tensor([1, 2, 3])


Dataloader practice:

Using the Fashion MNIST dataloader object, iterate over the batches, and calculate an interesting statistic. Make sure the statistic represent the entire data, not just a single batch. Hint- find a way to "update" the statistic along the batches.

In [65]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.ToTensor()
fashion_mnist = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
batch_size = 64
dataloader = DataLoader(fashion_mnist, batch_size=batch_size, shuffle=True)

total_sum = 0.0
total_count = 0

for images, _ in dataloader:
    # Sum the pixel values in the current batch
    total_sum += images.sum()
    # Count the number of pixels in the current batch
    total_count += images.numel()

# Calculate the mean pixel value for the entire dataset
mean_pixel_value = total_sum / total_count
print(f"Mean pixel value across the entire Fashion MNIST dataset: {mean_pixel_value:.4f}")


Mean pixel value across the entire Fashion MNIST dataset: 0.2860


## How to export an `HTML` file of your `ipynb`


1. Save your notebook and make sure all the cells have the expected output.
2. Download your notebook to your local machine.   `File-->Download-->Download ipynb`
3.  Reupload it so Colab can see it :  Click on the Files icon on the far left bar--> you should see your current kernel folder --> click `upload to session storage` --> upload your file.
4. Execute the following: `!jupyter nbconvert --to html /content/NOTEBOOKFILE.ipynb`
5. You should see the html file produced in your kernel's current folder. You can download it locally.
[link text](https://)

 END OF PyTorch BASICS